#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 20 14:56:07 2023

@author: evgeni
"""

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

# draw distributions
N=10000
cos_incs = np.random.uniform(-1,1,N)
incs = np.arccos(cos_incs) 
log_semis = np.random.uniform(-2,1,N)
semis = 10**log_semis

ecc_max = [max(0, (1 - 5/3*x**2)**0.5) for x in cos_incs] 

r_p_min = [x*(1-e) for (x,e) in zip(semis, ecc_max)]

#f_GW for eccentric binaries from Wen 2003
def f_GW_wen(a,e,m1,m2):
    G=6.674e-8
    au=1.49e13
    msun = 1.989e33
    
    return (G*(m1+m2)*msun)**0.5/np.pi / (a*au*(1-e**2))**1.5 * (1+e)**1.1954

f_wen = [f_GW_wen(x,e,10,10) for (x,e) in zip(semis, ecc_max)]

## plotting
plt.rc('text', usetex=False)
matplotlib.rcParams.update({'font.size': 20})

plt.figure(1, figsize=(10,8))
plt.subplots_adjust(left=0.07, bottom=0.1, right=0.99, top=0.98, wspace=0.21, hspace=0.25)

col = 'red'
cumul=-1
bins=200
plt.subplot(221)         
plt.hist(np.log10(semis), bins=bins, density=True, color=col,lw=3,  alpha=0.8, histtype='step', cumulative=cumul)
plt.xlabel(r'$\log_{10} a / \rm au$')
plt.subplot(222)         
plt.hist(np.log10(np.ones(N)-ecc_max), bins=bins, density=True, lw=3, color=col, alpha=0.8, histtype='step', cumulative=cumul)
plt.xlabel(r'$\log_{10} (1-e)$')

plt.subplot(223)
plt.hist(np.log10(r_p_min), bins=bins, density=True, color=col,lw=3, alpha=0.8, histtype='step', cumulative=cumul)
plt.xlabel(r'$\log_{10} r_p / \rm au$')

plt.subplot(224)
plt.hist(np.log10(f_wen), bins=bins, density=True, color=col, lw=3, alpha=0.8, histtype='step', cumulative=cumul)
plt.xlabel(r'$\log_{10} f_{\rm GW} / \rm Hz$')
#%%
plt.scatter(np.log10(f_wen), np.log10(semis))